### ISSUE TITLE
T/BCLK_SEL bits

### ISSUE THREAD

**Issue by gatecat** [Ravenslofty/mistral#10]
Some initial experimentation suggests that, contrary to expectations and the current docs,

`TCLK_SEL` actually controls the clock/enable for `FFT0` and `FFB1`.
`BCLK_SEL` actually controls the clock/enable for `FFB0` and `FFT1`.

i.e. the '1' FFs take their clock from the opposite half.

It seems like this behaviour doesn't apply to `[TB]SLOAD_EN` and `[TB]SCLR_DIS`. I haven't checked the ACLR selection yet.

**Comment by Ravenslofty** [comment]
Fixed the schematic with 8818c13
