### ISSUE TITLE
failed when build

### ISSUE THREAD

**Issue by baiyunping333** [Ravenslofty/mistral#19]
env:
```
ubuntu@10-9-99-245:~/mistral/build$ uname -a
Linux 10-9-99-245 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@10-9-99-245:~/mistral/build$ cat /etc/issue
Ubuntu 20.04 LTS \n \l
```
When I make with `make VERBOSE=1`, I get this
>/usr/bin/cmake -S/home/ubuntu/mistral -B/home/ubuntu/mistral/build --check-build-system CMakeFiles/Makefile.cmake 0
>/usr/bin/cmake -E cmake_progress_start /home/ubuntu/mistral/build/CMakeFiles /home/ubuntu/mistral/build/CMakeFiles>>/progress.marks
>make -f CMakeFiles/Makefile2 all
>make[1]: Entering directory '/home/ubuntu/mistral/build'
>make -f tools/CMakeFiles/tools.dir/build.make tools/CMakeFiles/tools.dir/depend
>make[2]: Entering directory '/home/ubuntu/mistral/build'
>cd /home/ubuntu/mistral/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/ubuntu/mistral /home/ubuntu/mistral/tools /home/ubuntu/mistral/build /home/ubuntu/mistral/build/tools /home/ubuntu/mistral/build/tools/CMakeFiles/tools.dir/DependInfo.cmake --color=
>make[2]: Leaving directory '/home/ubuntu/mistral/build'
>make -f tools/CMakeFiles/tools.dir/build.make tools/CMakeFiles/tools.dir/build
>make[2]: Entering directory '/home/ubuntu/mistral/build'
>make[2]: Nothing to be done for 'tools/CMakeFiles/tools.dir/build'.
>make[2]: Leaving directory '/home/ubuntu/mistral/build'
>[  4%] Built target tools
>make -f generator/CMakeFiles/generator.dir/build.make generator/CMakeFiles/generator.dir/depend
>make[2]: Entering directory '/home/ubuntu/mistral/build'
>cd /home/ubuntu/mistral/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/ubuntu/mistral /home/ubuntu/mistral/generator /home/ubuntu/mistral/build /home/ubuntu/mistral/build/generator /home/ubuntu/mistral/build/generator/CMakeFiles/generator.dir/DependInfo.cmake --color=
>make[2]: Leaving directory '/home/ubuntu/mistral/build'
>make -f generator/CMakeFiles/generator.dir/build.make generator/CMakeFiles/generator.dir/build
>make[2]: Entering directory '/home/ubuntu/mistral/build'
>make[2]: Nothing to be done for 'generator/CMakeFiles/generator.dir/build'.
>make[2]: Leaving directory '/home/ubuntu/mistral/build'
>[ 20%] Built target generator
>make -f libmistral/CMakeFiles/mistral.dir/build.make libmistral/CMakeFiles/mistral.dir/depend
>make[2]: Entering directory '/home/ubuntu/mistral/build'
>[ 21%] Generating e50f-r.bin
>cd /home/ubuntu/mistral/build/libmistral && ../generator/generator /home/ubuntu/mistral/libmistral/../data e50f /home/ubuntu/mistral/build/libmistral 1
>Killed
>
>make[2]: *** [libmistral/CMakeFiles/mistral.dir/build.make:264: libmistral/e50f-r.bin] Error 137
>make[2]: Leaving directory '/home/ubuntu/mistral/build'
>make[1]: *** [CMakeFiles/Makefile2:211: libmistral/CMakeFiles/mistral.dir/all] Error 2
>make[1]: Leaving directory '/home/ubuntu/mistral/build'
>make: *** [Makefile:130: all] Error 2

How can I do?

**Comment by gatecat** [comment]
Looks like it's running out of memory...

**Comment by Ravenslofty** [comment]
Yes, the Mistral build needs a good amount of memory, and it looks like it's getting killed by the kernel. I would suggest running the beginning of the build with `-j1` or whatever the cmake build equivalent is.
